### ISSUE TITLE
Stats pages not working

### ISSUE THREAD

**Issue by Elleiana** [The-Balance-FFXIV/balance-static#1000]
Stats and Materia pages are blank.
Information shows on the main job page, but isnt being pulled onto the specific Stats guide page.

Examples;
![image](https://user-images.githubusercontent.com/81540578/142739409-67c00501-d264-4048-a24b-b875ba9eca2e.png)
![image](https://user-images.githubusercontent.com/81540578/142739416-1201b1fa-3a3b-4216-8af0-eb4e8c6b8ac0.png)

**Comment by MlleCanary** [comment]
https://github.com/The-Balance-FFXIV/glam/pull/195
This was supposed to be fixed by this, and I think is still a Glam issue rather than static.
