### ISSUE TITLE
Adjustments to Author profiles at the bottom of guides

### ISSUE THREAD

**Issue by Elleiana** [The-Balance-FFXIV/balance-static#1001]
Author profiles need better distinction between names and discord profiles. 
Discord links should either feature a discord favicon, or at least have the bold text removed - so that it doesnt look like a continuation of the name on another line. 
Formatting guide in #frontend on discord doesn't feature any bold text. 

Example; 
![image](https://user-images.githubusercontent.com/81540578/142739496-bca38a8c-e7c2-4562-bc3b-49c8625da44d.png)

**Comment by MlleCanary** [comment]
I think this is a glam thing. Will look around more.

**Comment by nonowazu** [comment]
Fixed by The-Balance-FFXIV/glam#348
