### ISSUE TITLE
Footer for Encounters Empty

### ISSUE THREAD

**Issue by MlleCanary** [The-Balance-FFXIV/balance-static#1308]
![image](https://user-images.githubusercontent.com/88956860/148442219-6979201c-a9c1-4152-a81d-3f546b22483f.png)

The Encounters page is working, the footer is not. After playing hide and seek with it a bit, I am making an issue so others can hunt and hopefully fix it.

**Comment by zorianak** [comment]
In progress.

**Comment by zorianak** [comment]
Fixed now.
