### ISSUE TITLE
[Calli's records] Shit shouldn't be in exampleSite

### ISSUE THREAD

**Issue by zorianak** [The-Balance-FFXIV/balance-static#1373]
Our configurations should be in a /configurations/ folder, not under exampleSite - exampleSite looks (from a dev perspective) as though it's literally that - an example from creating the initial site.

This will make it much harder for us to onboard new devs. Making a milestone/ticket to track refactoring this once more pressing bugs are figured out.

**Comment by hintxiv** [comment]
@zorianak what configuration is under exampleSite currently?

**Comment by nonowazu** [comment]
There's some problems with this issue and it probably should be closed:

1. this is likely referring to [glam](https://github.com/The-Balance-FFXIV/glam/tree/main/exampleSite) and not this repo
2. `exampleSite` is the convention with hugo themes so you can preview the theme without having to conflate production content and theme in the same repo. You can find plenty of examples on the [hugo themes site](https://themes.gohugo.io/). Examples:
    1. [hugo-pacman-theme](https://github.com/coderzh/hugo-pacman-theme)
    2. [materialize-bp-hugo-theme](https://github.com/spech66/materialize-bp-hugo-theme)
    3. [strange-case](https://github.com/ExchangeRate-API/strange-case)
3. If you are putting production data in the theme's `exampleSite` directory, I would encourage you to not do that.

Onboarding devs should be as straightforward as having them read the following documentation and to submit issues for the things which aren't clear (which should be documented in the wiki for glam or this repo, as appropriate):

1. [hugo docs](https://gohugo.io/documentation/)
2. [tailwind docs](https://tailwindcss.com/)
3. [netlify's github documentation](https://www.netlifycms.org/docs/github-backend/)

**Comment by lailleo** [comment]
Closed per above response.
