### ISSUE TITLE
Editor preview styles broken

### ISSUE THREAD

**Issue by hintxiv** [The-Balance-FFXIV/balance-static#1946]
Snuck in as of #1935 - editor preview styles are now broken with the following ReferenceErrors:

![image](https://user-images.githubusercontent.com/65056303/190878465-d83d75b5-31c2-40b9-a7ba-f414c8907a52.png)

**Comment by nonowazu** [comment]
Can this be replicated over in the glam repo? If it can, I'll take a look at it there.

**Comment by nonowazu** [comment]
@hintxiv / @rexatlanti - or, if you want me to look directly, you can give me access to the repo in a non-committing role. Testing in glam, I don't see these issues.
