### ISSUE TITLE
Jobs landing page broken

### ISSUE THREAD

**Issue by ScrubbyXIV** [The-Balance-FFXIV/balance-static#547]
/jobs/_index.md is broken/non existent

![image](https://user-images.githubusercontent.com/65615038/140990066-fd81544e-c415-4621-a9fa-48e2a940942d.png)

**Comment by nonowazu** [comment]
We might to do something like this (in the *root* `_index.md`):

```md
---
# other options here
alias:
  - /jobs/
---
Whatever goes here
```

**Comment by nonowazu** [comment]
I changed the header to not link combat jobs to `/jobs/`, which should fix this for now.
