### ISSUE TITLE
All H1 need to be converted into H2 for markdown

### ISSUE THREAD

**Issue by OHaiDanny** [The-Balance-FFXIV/balance-static#702]
There are some hugo features that does not detect h1 (ex. Table of Contents which only reads h2 and beyond). Therefore we will need to change all h1 markdown into h2 markdown.

**Comment by MlleCanary** [comment]
All H1 headings converted to H2 and below. Some standardization implemented as anything past H4 beings to render smaller than the body text. This applies to all guides and pages for soft launch. 

(Possibly unnecessary note: this only applies to the Guide section, the general guides will not have this fix implemented and will need to have their H1s converted to H2s whenever we decide to put them live. High-end content guides will also need updated.)
