### ISSUE TITLE
Many dead links

### ISSUE THREAD

**Issue by jmerdich** [The-Balance-FFXIV/balance-static#905]
This is a great site with a lot of great info.... but some of it isn't written yet. As such, there are a ton of dead links outside the DoM/DoW pages, including *every item on the main menu*.

For example, on the home page, applying a 🚧 emoji to every dead link with `a[href="#"]::before { content: "🚧"; }` gives the following:

![image](https://user-images.githubusercontent.com/6345033/141887976-fcb19cc9-6ab3-422b-9a29-36887cd24c35.png)

These should either be removed or be given some visual indication that they do not have content (yet).

**Comment by lailleo** [comment]
The main menu is not meant to be functioning until hard launch. It should be fixed by then. Appreciate the feedback, all the same.
