### ISSUE TITLE
Author profiles not working

### ISSUE THREAD

**Issue by Elleiana** [The-Balance-FFXIV/balance-static#999]
Some guides have broken author profiles, despite looking correct in the editor interface.

- Paladin
   - Levelling
   - Basic
 
- White Mage
   - Levelling

- Machinist
   - Levelling
   - Openers
   - Basic

**Comment by MlleCanary** [comment]
This is due to the .json files not matching authors who were created before we knew they had to be entirely lowercase. 

Testing to see if changing the username field to lowercase to match the .json files will fix existing authors or if those need to be redone.

**Comment by MlleCanary** [comment]
I am going through and fixing all of these.
